	SUBROUTINE READ_TABLE
	PARAMETER (NFACE=127,NLAT=16,NTIME=32,NSL=31,NTHRM=46)
	REAL INSOLT(NTIME,0:NFACE,NLAT,NSL)		! solar input
	REAL TT(NTIME,0:NFACE,NLAT,NTHRM,NSL)	! the temperatures
C
	COMMON /TABLES/ INSOLT,TT
C
	OPEN (UNIT=41,FILE='fort.11',
	1	FORM='unformatted')
	DO ISL=1,NSL
	  READ (41) (((INSOLT(I,J,K,ISL),I=1,NTIME),J=0,NFACE),K=1,NLAT)
	  DO IT=1,NTHRM
	    READ (41) (((TT(I,J,K,IT,ISL),I=1,NTIME),J=0,NFACE),K=1,NLAT)
	  ENDDO
	ENDDO
	CLOSE (UNIT=41)
C
	SOLMIN = 1.E30
	SOLMAX = -SOLMIN
	DO ISL=1,NSL
	  DO K=1,NLAT
	    DO J=1,NFACE
	      DO I=1,NTIME
	        SOLMIN=MIN(SOLMIN,INSOLT(I,J,K,ISL))
	        SOLMAX=MAX(SOLMAX,INSOLT(I,J,K,ISL))
	      ENDDO
	    ENDDO
	  ENDDO
	ENDDO
	WRITE (*,*) SOLMIN,SOLMAX
	THMIN = 1.E30
	THMAX = -THMIN
	DO ISL=1,NSL
	  DO IT=1,NTHRM
	    DO K=1,NLAT
	      DO J=1,NFACE
	        DO I=1,NTIME
	          THMIN=MIN(THMIN,TT(I,J,K,IT,ISL))
	          THMAX=MAX(THMAX,TT(I,J,K,IT,ISL))
	        ENDDO
	      ENDDO
	    ENDDO
	  ENDDO
	ENDDO
	WRITE (*,*) THMIN,THMAX
	RETURN
	END
