C	read-WISE-NEATM-MCMC.f
C	gfortran -o read-WISE-NEATM-MCMC read-WISE-NEATM-MCMC.f ~/Ned.a
C
C	write D histogram on fort.2, "fine" on fort.32
C	writes D vs albedo scatter on fort.4
C
	PARAMETER (NMCX=1500000,NP=4)
	PARAMETER (NSKIP=1)
	PARAMETER (PVMAX = 1.5, TH1MAX = 1.0E4)
	REAL*4 P(NP,NMCX),D(NMCX),PV(NMCX)
	REAL*4 PIR2PV(NMCX),ETA(NMCX)
	INTEGER WGT(NMCX)
	CHARACTER*80 FN
	PARAMETER (NDH=123,NDF=NDH*10)
	PARAMETER (DTR = 57.2957795, PI=3.14159265)
	INTEGER DHIST(NDH),DFINE(NDF)
	INTEGER NL,LIST(9999)
	REAL*4 WW(9999)
	REAL*8 SW,SWD,SWDD,DIA,SDIA,SWA,SWAA,SWT,SWTT
C
	WRITE (*,FMT='(A,$)') 'Input mcmc file:'
	READ (*,FMT='(A)') FN
	NC = LNBLNK(FN)
	OPEN (UNIT=21,FILE=FN(1:NC))
	DO I=1,NSKIP
	  READ (21,*)
	ENDDO
	NMC = 1
	SWGTT = 0
	SWGT = 0
10	READ (21,FMT='(F8.5,3F9.5,F17.5,I5)',ERR=10,END=20) 
	1	(P(I,NMC),I=1,NP),CHSQ,WGT(NMC)
	SWGTT = SWGTT+WGT(NMC)
	DO I=1,NP
	  IF (ABS(P(I,NMC)).GT.23.) GO TO 10
	ENDDO
	NMC = NMC+1
	IF (NMC.LE.NMCX) GO TO 10
20	CLOSE (UNIT=21)
	NMC = NMC-1
C
	DO I=1,NDH
	  DHIST(I)=0
	ENDDO
	DO I=1,NDF
	  DFINE(I)=0
	ENDDO
	SW = 0
	SWD = 0
	SWDD = 0
	SWA = 0
	SWAA = 0
C
	WRITE (*,*) 'entering I=1..NMC=',NMC,' loop'
	WRITE (*,*) 'total weight:', SWGTT
	DO J=1,NMC
	  D(J) = EXP(P(4,J))
	  SW = SW+WGT(J)
	  SWD = SWD+WGT(J)*D(J)
	  SWDD = SWDD+WGT(J)*D(J)**2
	  ID = 1.0+23.*ALOG10(D(J)*1000.)
	  IF (ID.GE.1 .AND. ID.LE.NDH) DHIST(ID)=DHIST(ID)+WGT(J)
	  ID = 1.0+230.*ALOG10(D(J)*1000.)
	  IF (ID.GE.1 .AND. ID.LE.NDF) DFINE(ID)=DFINE(ID)+WGT(J)
	  PIR2PV(J) = EXP(P(2,J))
	  ALBEDO = EXP(P(1,J))
	  ALBEDO = ALBEDO*PVMAX/(ALBEDO+PVMAX)
	  PV(J) = ALBEDO
	  ETA(J) = EXP(P(3,J))
	  SWA = SWA+WGT(J)*ALBEDO
	  SWAA = SWAA+WGT(J)*ALBEDO**2
	  WRITE (4,FMT='(F10.4,F7.4,2H P)') D(J),PV(J)
	  IF(ETA(J).LT.999.) WRITE (3,FMT='(F10.4,F9.4,2H P)') D(J),ETA(J)
	ENDDO
C
	WRITE (*,*) 'out of 1..NMC loop'
	CLOSE (UNIT=3)
	CLOSE (UNIT=4)
C
	WRITE (2,FMT='(13I6)') DHIST
	WRITE (32,FMT='(13I6)') DFINE
C
	DIA = SWD/SW
	SDIA = SQRT(SWDD/SW-DIA**2)
	CALL MED1SIGMA(NMC,D,WGT,DMED,DM,DP)
	SDP = 100*ALOG(DP/DMED)
	SDM = 100*ALOG(DMED/DM)
C
	ALB = SWA/SW
	SALB = SQRT(SWAA/SW-ALB**2)
	CALL MED1SIGMA(NMC,PV,WGT,PVMED,PVM,PVP)
	SPVP = 100*ALOG(PVP/PVMED)
	SPVM = 100*ALOG(PVMED/PVM)
	CALL MED1SIGMA(NMC,PIR2PV,WGT,CMED,SCM,SCP)
	SCP = 100*ALOG(SCP/CMED)
	SCM = 100*ALOG(CMED/SCM)
	CALL MED1SIGMA(NMC,ETA,WGT,ETAMED,SETAM,SETAP)
	SETAP = 100*ALOG(SETAP/ETAMED)
	SETAM = 100*ALOG(ETAMED/SETAM)
C
	WRITE (*,9001) 'dia=',DIA,SDIA,' median',DMED,SDP,SDM
900	FORMAT(A,F9.4,A,F9.4,A,F9.4,A,F5.1,1H%)
9001	FORMAT(A,F9.4,3H+/-,F9.4,A,F9.4,1H+,F6.1,1H-,F6.1,1H%)
	WRITE (*,9001) 
	1	'p_V = ',ALB,SALB,' median',PVMED,SPVP,SPVM
901	FORMAT(A,1PE11.3,A,1PE11.3,A,0PF7.3,A,F7.3,A)
	WRITE (*,FMT='(A,F6.3,1H+,F5.1,1H-,F5.1,1H%)') 
	1	'p_IR/p_V=',CMED,SCP,SCM
	WRITE (*,FMT='(A,F6.3,1H+,F5.1,1H-,F5.1,1H%)') 
	1	'eta=',ETAMED,SETAP,SETAM
	STOP
	END

	SUBROUTINE MED1SIGMA(NMC,X,W,XMED,XM,XP)
	REAL X(*)
	INTEGER W(*)
	PARAMETER (NMCX=1500000)
	COMPLEX*8 C(NMCX)
	REAL V(3)
	SW = 0
	DO J=1,NMC
	  SW = SW+W(J)
	  C(J) = CMPLX(X(J),FLOAT(W(J)))
	ENDDO
	CALL CSORT(NMC,C)
	DO I=1,3
	  T = SW*(0.50+0.34*(I-2))
	  S = 0
	  DO J=1,NMC
	    S = S+AIMAG(C(J))
	    IF (S.GT.T) THEN
	      F = (T-(S-AIMAG(C(J))))/AIMAG(C(J))
	      V(I) = F*C(J)+(1-F)*C(J-1)
	      GO TO 100
	    ENDIF
	  ENDDO
100	ENDDO
	XMED = V(2)
	XM = V(1)
	XP = V(3)
	RETURN
	END
