	LOGICAL FUNCTION ASPECT(T,A)
C
C	modified 6-Aug-2005 to be a logical function
C
C	VERSION ASPECT1.FTN 29-MAR-83, THAT TRIES TO SIMULATE THE DEAD BAND
C		BEHAVIOUR OF THE COBE SUN SERVO
C
C	DUMMY ROUTINE FOR TESTS AND SIMULATIONS
C	BY NED WRIGHT 28-MAR-83
C
C	INPUT: T REAL*8 TIME SINCE 5/24/68 IN SECONDS
C	OUTPUT: A REAL*4 3X3 ARRAY, ROTATION MATRIX
C		B(CEL)=A*B(COBE)
C		WHERE B IS A 3 VECTOR
C
	REAL*8 T
	REAL*4 A(3,3),R(3,3)
	CALL AGEN(T,A,R)
	ASPECT = .TRUE.
	RETURN
	END
