	SUBROUTINE CONSTELLATION(C,CON)
C	finds constellation for a J2000 position entered as a unit
C	vector in C
	REAL*4 C(3)
	CHARACTER*3 CON
C
	REAL*4 C75(3)
	REAL*4 P(3,3)
C	precess to 1875
	CALL PREMAT(1875.0,P)
	CALL MAV(P,C,C75)
	DO I=1,3
	  C75(I) = C(I)+C75(I)
	ENDDO
	CALL C_TO_RADEC(C75,RA,DEC)
	RA = DTR*RA/15
	DEC = DTR*DEC
	OPEN (UNIT=22,FILE='/Users/ned/missions/WISE/constellation.txt',
	1	STATUS='old')
30	READ (22,120,END=220,ERR=230) RAL,RAU,DECL,CON
120	FORMAT(2F8.4,F9.4,1X,A3)
	IF (DECL.GT.DEC) GOTO 30
10	IF (RAU.LE.RA) THEN
	  READ (22,120,END=220,ERR=230) RAL,RAU,DECL,CON
	  GO TO 10
	ENDIF
20	IF (RAL.GT.RA) THEN
	  READ (22,120,END=220,ERR=230) RAL,RAU,DECL,CON
	  GO TO 20
	ENDIF
C IF CONSTELLATION HAS BEEN FOUND, WRITE RESULT AND RERUN PROGRAM FOR
C  NEXT ENTRY.  OTHERWISE, CONTINUE THE SEARCH BY RETURNING TO RAU
	IF (RA.GE.RAL.AND.RA.LT.RAU.AND.DECL.LE.DEC) THEN
	  CLOSE (UNIT=22)
	  RETURN
	ELSE IF (RAU.LT.RA) THEN
	  GO TO 10
	ELSE
	  WRITE (*,*) 'bad constellation at ',C
	  STOP
	ENDIF
220	WRITE (*,*) 'EOF in constellation.txt'
	STOP
230	WRITE (*,*) 'Input error in constellation.txt'
	END
