	SUBROUTINE DIRBE_NABORS(NPIX,NN,NABES)
C
C	GIVEN INPUT PIXEL NPIX, FIND ITS NEIGHBORS
C	PUT # OF NEIGHBORS INTO NN
C	AND PIXEL NUMBERS OF THE NEIGHBORS INTO NABES(1),...NABES(NN)
C
	INTEGER*4 NABES(4),NPIX,JPIX,IXTAB,IYTAB
	REAL*4 C(3)
	SAVE /DRBBIT/
	COMMON /DRBBIT/ IXTAB(256),IYTAB(256)
C
	IF(IXTAB(256).EQ.0) THEN		!Make sure the bit table is set
	  C(1)=1.
	  CALL DIRBE_PIXNO(C,NABES)
	ENDIF
	NN=4				!Always 4 neighbors
	NFACE=NPIX/65536		!Get face
	JPIX=NPIX-NFACE*65536
	IX=0
	IY=0
	IP=1
10	IF(JPIX.EQ.0) GO TO 100		!Break up even and odd bits
	  ID=MOD(JPIX,2)
	  JPIX=JPIX/2
	  IX=ID*IP+IX
	  ID=MOD(JPIX,2)
	  JPIX=JPIX/2
	  IY=ID*IP+IY
	  IP=2*IP
	  GO TO 10
C
100	CALL EDGCHK(NFACE,IX+1,IY,256,MFACE,JX,JY)
	NABES(1)=MFACE*65536+IXTAB(JX+1)+IYTAB(JY+1)
	CALL EDGCHK(NFACE,IX,IY+1,256,MFACE,JX,JY)
	NABES(2)=MFACE*65536+IXTAB(JX+1)+IYTAB(JY+1)
	CALL EDGCHK(NFACE,IX-1,IY,256,MFACE,JX,JY)
	NABES(3)=MFACE*65536+IXTAB(JX+1)+IYTAB(JY+1)
	CALL EDGCHK(NFACE,IX,IY-1,256,MFACE,JX,JY)
	NABES(4)=MFACE*65536+IXTAB(JX+1)+IYTAB(JY+1)
	RETURN
	END
