	SUBROUTINE DMR_CENPIX(NDMR,C)
C
C	FASTER VERSION USING /SPRCNPX/
C	19-SEP-85
C
	INTEGER NDMR
	REAL*4 C(3)				!Output unit vector
C
	INTEGER*2 IX,IY
	COMMON /COBE_SPRCNPX/ IX(0:1023),IY(0:1023)
	IF(IX(1023).NE.31) CALL COBE_SPRCNPX_SET
C
	NFACE=NDMR/1024
	M=MOD(NDMR,1024)
	JX=IX(M)
	JY=IY(M)
C
	X=(JX-15.5)/16.				!Database coordinates.  Range
	Y=(JY-15.5)/16.				! -1 -> 1 covers the square face
	CALL FORWARD_CUBE(X,Y,XI,ETA)
	CALL XYAXIS(NFACE,XI,ETA,C)
	RETURN
	END
