	SUBROUTINE GCMOON(T,PMOON)
C
C	NEW VERSION USING EPHEM, 30-AUG-83
C
C	INPUT T REAL*8 SECONDS SINCE 5/24/68
C
C	OUTPUT REAL*4 PMOON(3) GEOCENTRIC VECTOR POS'N OF MOON
C	IN KILOMETERS
C
	PARAMETER (AEARTH=6378.16)	! equatorial radius of Earth
	REAL*8 T
	REAL*4 PMOON(3)
	CALL EPHEM(0,T,PMOON)
	DO 100 I=1,3
100	PMOON(I) = AEARTH*PMOON(I)
	RETURN
	END
