	REAL*8 FUNCTION GMT2T68(GMT)
C
C	CONVERT THE STRING IN GMT 'YYDDDHHMMSSFFF' FORMAT INTO
C	T68 REAL*8 SECONDS SINCE 5/24/68 00:00:00 UTC FORMAT
C	IF GMT = 'NOW' GET CURRENT SYSTEM TIME AND CONVERT THAT
C
	CHARACTER*14 GMT
	CHARACTER*24 FDATEOUT
	CHARACTER*3 ZONE
	INTEGER IY,ID,MON,IH,MINUTE
	REAL*4 SECOND
	REAL*8 GREENWICH
 	REAL*8 T68
	IF (INDEX(GMT,'NOW').GT.0) THEN
C	version for Unix library
	  CALL FDATE(FDATEOUT)
	  MON = (INDEX(
	1	' Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec '
	2	,FDATEOUT(4:8))-1)/4+1
	  DO WHILE (INDEX(FDATEOUT,':').GT.0)
	    I = INDEX(FDATEOUT,':')
	    FDATEOUT(I:I) = ' '
	  ENDDO
	  READ (FDATEOUT(8:24),*) 
	1	ID, IH, MINUTE, IS, IY 
	  SECOND = IS
	  CALL TIME_TAG(IY,MON,ID,IH,MINUTE,SECOND,T68)
	  GMT2T68 = GREENWICH(T68,ZONE)
	ELSE
 	  READ (GMT,FMT='(I2,I3,2I2,F5.3)') IY,ID,IH,MINUTE,SECOND
	  IY = 1900+IY
	  IF (IY.LT.1968) IY=IY+100
	  MON = 1
	  CALL TIME_TAG(IY,MON,ID,IH,MINUTE,SECOND,T68)
	  GMT2T68 = T68
	ENDIF
	RETURN
	END
