	REAL*8 FUNCTION GREENWICH(PT,ZONE)
C	given a Pacific time T68, returns GREENWICH time (7 or 8 hours ahead)
C	with ZONE = `PDT' or `PST'
	REAL*8 PT
	REAL*8 T68
	CHARACTER*3 ZONE
	INTEGER WEEKDAY
	REAL*8 SPRINGFORWARD,FALLBACK
	CALL T68_TO_UTC(PT,IY,MON,ID,IH,MINUTE,SECOND)
	IF (IY.GE.2007) THEN
C	new rules
C	find second Sunday in March
	  DO ID=8,14
	    IDW = WEEKDAY(IY,3,ID)
	    IF (IDW.EQ.0) THEN
	      CALL TIME_TAG(IY,3,ID,2,0,0.,SPRINGFORWARD)
	    ENDIF
	  ENDDO
C	find first Sunday in November
	  DO ID=7,1,-1
	    IDW = WEEKDAY(IY,11,ID)
	    IF (IDW.EQ.0) THEN
	      CALL TIME_TAG(IY,11,ID,2,0,0.,FALLBACK)
	    ENDIF
	  ENDDO
	ELSE
C	old rules
C	find first Sunday in April
	  DO ID=1,7
	    IDW = WEEKDAY(IY,4,ID)
	    IF (IDW.EQ.0) THEN
	      CALL TIME_TAG(IY,4,ID,2,0,0.,SPRINGFORWARD)
	    ENDIF
	  ENDDO
C	find last Sunday in October
	  DO ID=31,25,-1
	    IDW = WEEKDAY(IY,11,ID)
	    IF (IDW.EQ.0) THEN
	      CALL TIME_TAG(IY,10,ID,2,0,0.,FALLBACK)
	    ENDIF
	  ENDDO
	ENDIF
	T68 = PT+8*3600
	ZONE = 'PST'
	IF (PT.LT.SPRINGFORWARD) GO TO 100
	T68 = PT+7*3600
	ZONE = 'PDT'
	IF (PT.LT.FALLBACK) GO TO 100
	T68 = PT+8*3600
	ZONE = 'PST'
100	GREENWICH = T68
	RETURN
	END
