	INTEGER*2 FUNCTION I2FITS(B)
	BYTE B(2)
	BYTE BB(2)
	INTEGER*2 J
	EQUIVALENCE (BB,J)
	BYTE BT(2) /1,2/
	INTEGER*2 JT
	EQUIVALENCE (BT,JT)
	IF (JT.EQ.258) THEN
	  BB(1) = B(1)
	  BB(2) = B(2)
	ELSE IF (JT.EQ.513) THEN
	  BB(1) = B(2)
	  BB(2) = B(1)
	ELSE
	  STOP 'bad JT'
	ENDIF
	I2FITS = J
	RETURN
	END
