	LOGICAL FUNCTION IFNUM(TOKEN,VALUE)
C
C	returns TRUE if the string in TOKEN is a valid number.
C	If so, VALUE is set to the value of the number
C
	CHARACTER*(*) TOKEN
	CHARACTER*1 C
	REAL*8 VALUE,DIV,SIGN
	LOGICAL POINT,POWER
	VALUE=0.
	DIV=1.
	SIGN=1.
	IFNUM=.TRUE.
	POINT=.FALSE.
	POWER=.FALSE.
	IPOWER=0
	ISPOWER=1
	DO I=1,LEN(TOKEN)
		C=TOKEN(I:I)
		ID=ICHAR(C)-ICHAR('0')
		IF(C.EQ.'.') THEN
			IF(POINT) IFNUM=.FALSE.
			POINT=.TRUE.
		ELSE IF(C.EQ.'-') THEN
			IF(POWER) THEN
				IF(ISPOWER.LT.0) IFNUM=.FALSE.
				ISPOWER=-ISPOWER
			ELSE
				IF(SIGN.LT.0.) IFNUM=.FALSE.
				SIGN=-SIGN
			END IF
		ELSE IF(C.EQ.'+') THEN
			CONTINUE
		ELSE IF(C.EQ.'E' .OR. C.EQ.'e') THEN
			POWER=.TRUE.
		ELSE IF(ID.GE.0 .AND. ID.LE.9) THEN
			IF(POWER) THEN
				IPOWER=10*IPOWER+ID
			ELSE
				VALUE=VALUE*10.D0+ID
				IF(POINT) DIV=10.D0*DIV
			END IF
		ELSE IF(C.EQ.':') THEN
			IF(POINT.OR.POWER) IFNUM=.FALSE.
			VALUE=0.6D0*VALUE
		ELSE
			IFNUM=.FALSE.
		END IF
	END DO
	VALUE=SIGN*(VALUE/DIV)*10.D0**(ISPOWER*IPOWER)
	RETURN
	END
