	INTEGER FUNCTION LENSTR(STRING)
C	returns the non-blank length of a string
	CHARACTER*(*) STRING
	I = LEN(STRING)
	IF (I.LE.0) GO TO 100
	DO WHILE (STRING(I:I).EQ.' ')
	  I = I-1
	  IF (I.LE.0) GO TO 100
	ENDDO
100	LENSTR = I
	RETURN
	END
