	REAL FUNCTION LT_DN(T68)
C	computes the local time at the descending node for T68 seconds
C	after 24 May 1968
	REAL*8 T68,TDNC,T_DN
	REAL*4 LAT,LONG
	T_DN = TDNC(T68)
	CALL LATLONG(T_DN,LAT,LONG)
	CALL UTC(T_DN,IYEAR,MONTH,IDAY,IHOUR,IMINUTE,SECOND)
	TIME = IHOUR+(IMINUTE+SECOND/60)/60+LONG/15
	DO WHILE (TIME.LT.0) 
	  TIME=TIME+24
	ENDDO
	TIME = MOD(TIME,24.)
	LT_DN = TIME
	RETURN
	END
