	SUBROUTINE NORM(A)
C
C	NORMALIZES A THREE VECTOR
C
	DIMENSION A(3)
	AM=MAX(ABS(A(1)),ABS(A(2)),ABS(A(3)))
	IF(AM.GT.1.E10) THEN
	  DO I=1,3
	    A(I)=A(I)/AM
	  ENDDO
	ELSE IF (AM.EQ.0.) THEN
	  A(1) = 1.0
	  A(2) = 0.0
	  A(3) = 0.0
	ENDIF
	AA=SQRT(A(1)**2+A(2)**2+A(3)**2)
	DO I=1,3
	  A(I)=A(I)/AA
	ENDDO
	RETURN
	END
