	SUBROUTINE ORBIT_CONVERT(ORB,TOSC,INC,NODE,ARG,A,RATE,E,ME)
C	ROUTINE TO CONVERT ORBIT IN ECLIPTIC COORDINATES TO INTERNAL FORM
	DIMENSION ORB(10)
	REAL INC,NODE,ME
	PARAMETER (PI=3.1415927,TWOPI=6.2831853,DTR=57.29578)
	ORB(2)=A
	ORB(3)=E
	OMEGA=RATE/DTR
	ORB(10)=OMEGA
	DT=ME/DTR/OMEGA
	ORB(1)=TOSC-DT
	DO 10 I=4,9
10	ORB(I)=0.
	ORB(4)=1.
	ORB(8)=1.
	SA=SIN(ARG/DTR)
	CA=COS(ARG/DTR)
	DO 20 I=4,7,3
	T=CA*ORB(I)-SA*ORB(I+1)
	ORB(I+1)=CA*ORB(I+1)+SA*ORB(I)
20	ORB(I)=T
	SI=SIN(INC/DTR)
	CI=COS(INC/DTR)
	DO 30 I=5,8,3
	T=CI*ORB(I)-SI*ORB(I+1)
	ORB(I+1)=CI*ORB(I+1)+SI*ORB(I)
30	ORB(I)=T
	SN=SIN(NODE/DTR)
	CN=COS(NODE/DTR)
	DO 40 I=4,7,3
	T=CN*ORB(I)-SN*ORB(I+1)
	ORB(I+1)=CN*ORB(I+1)+SN*ORB(I)
40	ORB(I)=T
	RETURN
	END
