	SUBROUTINE ORTH2(V,W,X)
C
C	CONSTRUCT AN ORTHONORMAL TRIPLET WITH X-AXIS ALONG V, STORED IN V
C	Y-AXIS IN THE VW PLANE, STORED IN W
C	AND Z-AXIS FORMING RIGHT-HANDED SYSTEM, STORED IN X
C
	REAL*4 V(3),W(3),X(3)
	CALL NORM(V)
	VW=DOT(V,W)
	DO 10 I=1,3
10	W(I)=W(I)-VW*V(I)
	WM = MAX(ABS(W(1)),ABS(W(2)),ABS(W(3)))
	IF (WM.LE.0.) THEN
	  J = 1
	  B = ABS(V(1))
	  DO K=2,3
	    IF (ABS(V(K)).GT.B) THEN
	      B = ABS(V(K))
	      J = K
	    ENDIF
	  ENDDO
	  K = J+1
	  IF (K.GT.3) K = K-3
	  W(K) = 1.
	ENDIF
	CALL NORM(W)
	CALL CROSS(V,W,X)
	RETURN
	END
