	COMPLEX*16 FUNCTION QRATE(QQ,SCANRATE,DT)
C
C	apply SCANRATE in arcmin/sec for DT seconds to quaternion QQ
C
	COMPLEX*16 QQ
	REAL*4 SCANRATE(3)
	REAL*8 DT
	REAL*4 AXIS(3)
	COMPLEX*16 QGEN,QMUL
	PARAMETER (DTR = 57.295779513082)
	DO J=1,3
	  AXIS(J) = SCANRATE(J)
	ENDDO
C	rate in radians/seconds
	RATE = SQRT(DOT(AXIS,AXIS))/(60*DTR)
	CALL NORM(AXIS)
	TH = DT*RATE
	ST2 = SIN(TH/2.)
	QRATE = QMUL(QQ,
	1	QGEN(AXIS(1)*ST2,AXIS(2)*ST2,AXIS(3)*ST2,COS(TH/2.)))
C	WRITE (*,*) TH,ST2,RATE,DT
	RETURN
	END
