	COMPLEX*16 FUNCTION QXR(SCALAR,Q)
C	real SCALAR times quaterion Q
	REAL*4 SCALAR
	REAL*4 Q(4)
	REAL*4 P(4)
	COMPLEX*16 QQ
	EQUIVALENCE (QQ,P)
	DO I=1,4
	  P(I) = SCALAR*Q(I)
	ENDDO
	QXR = QQ
	RETURN
	END
