	SUBROUTINE READ_ORBITS
C
C	READS ASTEROID INFORMATION INTO COMMON BLOCK
C
C	ASTEROID COMMON BLOCK
C
	PARAMETER (NAST=26)
	COMMON /ASTEROID_ORBITS/ JD(2),ND,ORB(10,2,NAST)
C
	REAL*8 JD
	INTEGER*4 ND
	REAL*4 ORB
C
	REAL*4 INC,NODE,MM,ME
	OPEN (UNIT=18,FILE='ASTORBITS',STATUS='OLD')
	READ (18,900) JD
900	FORMAT(2D10.0)
901	FORMAT(10X,7F10.4)
	ND=2
	IF(JD(2).LE.0.) ND=1
	DO N=1,NAST
	  DO I=1,ND
	    READ(18,901,END=100) INC,NODE,ARG,A,MM,E,ME
	    TOSC=JD(I)-JD(1)
	    CALL ORBIT_CONVERT(ORB(1,I,N),TOSC,INC,NODE,ARG,A,MM,E,ME)
	  ENDDO
	ENDDO
100	CLOSE(UNIT=18)
	RETURN
	END
