	SUBROUTINE RTODMS(R,ID,IM,S)
C
C	CONVERTS INPUT RADIANS R INTO INTEGER DEGREES, MINUTES AND REAL 
C	SECONDS IN ID,IM,S.  FAILS FOR -0 30' ETC BECAUSE VAX DOESN'T 
C	HAVE A MINUS ZERO
C
	PARAMETER (PI=3.1415927,TWOPI=6.2831853,DTR=57.29577951)
	V=ABS(R)*DTR
	ID=V
	V=60.*(V-FLOAT(ID))
	IM=V
	S=60.*(V-FLOAT(IM))
	IF(R.LT.0.) ID=-ID
	RETURN
	END
