	SUBROUTINE SATELLITE(ABUF1,ABUF2,NT,TIN,LAT,LONG,
	1	AZOUT,ELOUT,DOUT,SEL,SSL)
	CHARACTER*(*) ABUF1,ABUF2
	REAL*8 TIN(NT)
	REAL LAT,LONG
	REAL*4 DM(14400)
	CALL SATELLITE2(ABUF1,ABUF2,NT,TIN,LAT,LONG,
	1	AZOUT,ELOUT,DOUT,SEL,SSL,DM)
	RETURN
	END
