      SUBROUTINE SPLSET(NP,X,Y,TAB)
C
C	SETS UP TAB FOR SPLINE
C	THERE ARE NP X VALUES IN THE INPUT ARRAY X: X(1)<X(2)<X(3)...
C	AND NP CORRESPONDING Y VALUES IN ARRAY Y
C	TAB IS A STORAGE AREA OF NP VALUES THAT SPLSET SETS EQUAL TO
C	THE SECOND DERIVATIVES OF Y
C	A NATURAL SPLINE IS USED, WITH Y'' = 0 AT THE BOUNDARY
C
      CALL SPLINSET(X,Y,NP,1.E31,1.E31,TAB)
      RETURN
      END
