	SUBROUTINE TERRESTIAL(T,R)
C
C	FOR INPUT TIME T, REAL*8 SECONDS SINCE 5/24/68
C	RETURNS REAL*4 R(3): VECTOR POSITION WRT CENTER OF EARTH
C	UNITS ARE KILOMETERS, +Z AT NORTH POLE, +X TOWARD GREENWICH
C
	REAL*8 T
C
	REAL*4 XYZ(3),R(3)
C
C	COMPUTE GREENWICH SIDEREAL TIME IN RADIANS
	SIDTIM=GST(T)
	CT=COS(SIDTIM)
	ST=SIN(SIDTIM)
	CALL ORBIT(T,XYZ)
C	ROTATE TO EARTH FIXED COORDINATES
	R(3)=XYZ(3)
	R(1)=CT*XYZ(1)+ST*XYZ(2)
	R(2)=CT*XYZ(2)-ST*XYZ(1)
	RETURN
	END
