	SUBROUTINE TOKENIZE(INPUT,NTOKEN,L)
C
C	takes an input string INPUT and breaks it into NTOKEN tokens
C	these tokens are the substrings INPUT(L(i,1):L(i,2)) for i=1..NTOKEN
C
	CHARACTER*(*) INPUT
	CHARACTER*1 B
	INTEGER NTOKEN,L(100,2)
	LOGICAL INTOKEN
	NTOKEN=0
	NC=LEN(INPUT)
	INTOKEN=.FALSE.
	DO MC=1,NC
		B=INPUT(MC:MC)
		IF(B.EQ.' ' .OR. B.EQ.CHAR(9) .OR. B.EQ.',') THEN
			IF(INTOKEN) THEN
				L(NTOKEN,2)=MC-1
				INTOKEN=.FALSE.
			END IF
		ELSE
			IF(.NOT.INTOKEN) THEN
				NTOKEN=NTOKEN+1
				L(NTOKEN,1)=MC
				INTOKEN=.TRUE.
			END IF
		END IF
	END DO
	IF(INTOKEN) L(NTOKEN,2)=NC
	RETURN
	END
